/**
 * 🔍 GRAPHQL QUERIES - CONSULTAS DE LECTURA
 *
 * Responsabilidad: Definir queries GraphQL para obtener datos
 * Flujo: Importado por hooks → Ejecutado por GraphQL client
 */

export {
  GET_CONVOCATORIAS_QUERY,
  GET_CONVOCATORIA_QUERY,
  GET_CONVOCATORIA_POR_REQUERIMIENTO_QUERY
} from './convocatorias.queries'

export {
  OBTENER_FORMULARIO_CONFIG_QUERY,
  OBTENER_FORMULARIO_CONFIG_POR_ID_QUERY,
  LISTAR_FORMULARIOS_CONFIG_QUERY
} from './formulario-config.queries'

export {
  LISTAR_APLICACIONES_QUERY,
  OBTENER_APLICACION_QUERY,
  OBTENER_ESTADISTICAS_CONVOCATORIA_QUERY,
  GET_KANBAN_DATA_QUERY
} from './aplicacion.queries'

// Candidato queries
export {
  LISTAR_CANDIDATOS_QUERY,
  BUSCAR_CANDIDATO_POR_DNI_QUERY,
  LISTAR_CANDIDATOS_ENCRYPTED_QUERY,
  OBTENER_CANDIDATO_ENCRYPTED_QUERY
} from './candidato.queries'

// Entrevista de llamada queries
export {
  OBTENER_ENTREVISTA_LLAMADA_QUERY,
  OBTENER_ENTREVISTA_LLAMADA_POR_APLICACION_QUERY,
  EXISTE_ENTREVISTA_LLAMADA_PARA_APLICACION_QUERY,
  LISTAR_ENTREVISTAS_LLAMADA_QUERY
} from './entrevista-llamada.queries'

// Entrevista regular queries
export {
  OBTENER_ENTREVISTA_REGULAR_QUERY,
  OBTENER_ENTREVISTA_REGULAR_POR_APLICACION_QUERY,
  EXISTE_ENTREVISTA_REGULAR_PARA_APLICACION_QUERY,
  LISTAR_ENTREVISTAS_REGULARES_QUERY,
  CONTAR_ENTREVISTAS_REGULARES_QUERY
} from './entrevista-regular.queries'

// Historial candidato queries
export {
  OBTENER_HISTORIAL_APLICACION_QUERY,
  OBTENER_HISTORIAL_CANDIDATO_QUERY,
  LISTAR_HISTORIAL_QUERY,
  OBTENER_ULTIMO_CAMBIO_ESTADO_QUERY,
  GENERAR_ESTADISTICAS_CONVERSION_QUERY
} from './historial-candidato.queries'

// Personal queries
export {
  BUSCAR_EMPLEADOS_QUERY
} from './personal.queries'

// Usuario queries
export {
  LIST_USUARIOS_PAGINATED_QUERY
} from './usuario.queries'

// Referencia queries
export {
  LISTAR_REFERENCIAS_QUERY,
  OBTENER_REFERENCIA_QUERY,
  LISTAR_REFERENCIAS_POR_APLICACION_QUERY
} from './referencia.queries'

// Debida Diligencia queries
export {
  OBTENER_DEBIDA_DILIGENCIA_QUERY,
  OBTENER_DEBIDA_DILIGENCIA_POR_APLICACION_QUERY,
  EXISTE_DEBIDA_DILIGENCIA_QUERY,
  LISTAR_DEBIDAS_DILIGENCIAS_QUERY,
  CONTAR_DEBIDAS_DILIGENCIAS_QUERY
} from './debida-diligencia.queries'
